[package]
name = "pd2tools-rust"
version = "0.1.0"
authors = ["Kythyria Tieran <kythyria@berigora.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dokan = "0.1.0"
widestring = "0.4.3"
winapi = "0.3.9"
fnv = "1.0.7"
clap = "2.33.3"
xmlwriter = "0.1.0"
nom = "6.1.2"