[package]
name = "pd2tools-macros"
version = "0.1.0"
authors = ["Kythyria Tieran <kythyria@berigora.net>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.72"
quote = "1.0.9"
proc-macro2 = "1.0.27"