name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache cargo registry
      uses: actions/cache@v2
      continue-on-error: false
      with:
        path: |
          %USERPROFILE%\.cargo\registry
          %USERPROFILE%\.cargo\git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**\Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build
      run: cargo build --verbose --release
    - uses: actions/upload-artifact@v2
      with:
        path: target/release/pd2tools-rust.exe
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest version"
        files: |
          target/release/pd2tools-bundlefs.exe
          target/release/pd2tools.exe
#    - name: Run tests
#      run: cargo test --verbose
